server:
  port: 80
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true # 消费者启动时，是否拉取eureka Server服务的列表只读备份，然后缓存到本地
    registry-fetch-interval-seconds: 5 # 每隔5秒重新获取并更新数据
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #设置hystrix的超时时间为1秒
feign:
  circuitbreaker:
    enabled: true # 开启Feign的熔断功能