server:
  port: 8080
leyou:
  sms:
    accessKeyId: LTAI5tFGBM6crNGGPgEWufLw # 你自己的accessKeyId
    accessKeySecret: hz1U8ZZbMqn4MRqD52IGuL2eOicxkd # 你自己的AccessKeySecret
    signName: 阿里云短信测试 # 签名名称
    verifyCodeTemplate: SMS_154950909 # 模板名称