server:
  port: 10010
spring:
  application:
    name: itcast-zuul
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # ?????????????????????????
      routes:
        - id: service-provider
#          uri: https://www.baidu.com
          uri: lb://service-provider # ??????????
          predicates:
            - Path=/service-provider/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka